### ISSUE TITLE
Travis Test failing timeout TestStartLatestAction

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-go#35]
This Travis build failed today
https://travis-ci.org/apache/incubator-openwhisk-runtime-go/jobs/381072767#L1150

Test TestStartLatestAction It doesn't return 
```
=== RUN   TestStartLatestAction
2018/05/19 13:41:00 starting ./action/1/main
2018/05/19 13:41:00 run: start
2018/05/19 13:41:00 run: end
2018/05/19 13:41:00 removing the failed action in ./action/1/
2018/05/19 13:41:00 starting ./action/2/main
2018/05/19 13:41:00 run: start
2018/05/19 13:41:00 logger: start
2018/05/19 13:41:00 service: start
2018/05/19 13:41:00 >>>x
2018/05/19 13:41:00 <<<1
2018/05/19 13:41:00 starting ./action/3/main
2018/05/19 13:41:00 run: start
2018/05/19 13:41:00 stopping old executor
2018/05/19 13:41:00 stopping
2018/05/19 13:41:00 terminated upon request
2018/05/19 13:41:00 service: end
2018/05/19 13:41:00 service: start
2018/05/19 13:41:00 >>>y
2018/05/19 13:41:00 logger: start
2018/05/19 13:41:00 logger: end
2018/05/19 13:41:00 run: end
SIGQUIT: quit
PC=0x45c131 m=0 sigcode=0
goroutine 0 [idle]:
runtime.futex(0x92b248, 0x0, 0x0, 0x0, 0x0, 0xc420030000, 0x0, 0x0, 0x7fffab085338, 0x41083b, ...)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/runtime/sys_linux_amd64.s:530 +0x21
runtime.futexsleep(0x92b248, 0x7fff00000000, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/runtime/os_linux.go:45 +0x4b
runtime.notesleep(0x92b248)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/runtime/lock_futex.go:151 +0x9b
runtime.stopm()
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/runtime/proc.go:1952 +0xe5
runtime.exitsyscall0(0xc420080480)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/runtime/proc.go:3129 +0x109
runtime.mcall(0x0)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/runtime/asm_amd64.s:351 +0x5b
goroutine 1 [chan receive]:
testing.(*T).Run(0xc4201900f0, 0x765970, 0x15, 0x7781f8, 0x486ee6)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc420190000)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc420190000, 0xc420065d58)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:777 +0xd0
testing.runTests(0xc42000c100, 0x923180, 0x6, 0x6, 0x0)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc420164000, 0x0)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:978 +0x171
github.com/apache/incubator-openwhisk-runtime-go/openwhisk.TestMain(0xc420164000)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-runtime-go/openwhisk/util_test.go:168 +0x83
main.main()
	_testmain.go:154 +0x208
goroutine 5 [chan receive]:
github.com/apache/incubator-openwhisk-runtime-go/openwhisk.TestStartLatestAction(0xc4201900f0)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-runtime-go/openwhisk/actionProxy_linux_test.go:61 +0x3ad
testing.tRunner(0xc4201900f0, 0x7781f8)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/testing/testing.go:824 +0x2e0
goroutine 26 [chan send]:
github.com/apache/incubator-openwhisk-runtime-go/openwhisk.(*Executor).run(0xc4200a1e50)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-runtime-go/openwhisk/executor.go:107 +0x18b
created by github.com/apache/incubator-openwhisk-runtime-go/openwhisk.(*Executor).Start
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-runtime-go/openwhisk/executor.go:178 +0x5e
goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x7f768a571470, 0x72, 0xc420043c98)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200a1dc8, 0x72, 0xffffffffffffff01, 0x79fd00, 0x8ef608)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4200a1dc8, 0xc420197001, 0x1000, 0x1000)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4200a1db0, 0xc420197000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/internal/poll/fd_unix.go:157 +0x17d
os.(*File).read(0xc42009e138, 0xc420197000, 0x1000, 0x1000, 0xc420047000, 0x0, 0xc420043da0)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc42009e138, 0xc420197000, 0x1000, 0x1000, 0x1000, 0x1000, 0x721740)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/os/file.go:107 +0x6a
bufio.(*Scanner).Scan(0xc420164200, 0x79f280)
	/home/travis/.gimme/versions/go1.10.2.linux.amd64/src/bufio/scan.go:208 +0xbf
github.com/apache/incubator-openwhisk-runtime-go/openwhisk.(*Executor).service(0xc4200a1e50)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-runtime-go/openwhisk/executor.go:161 +0x209
created by github.com/apache/incubator-openwhisk-runtime-go/openwhisk.(*Executor).Start
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-runtime-go/openwhisk/executor.go:185 +0x155
goroutine 9 [chan receive]:
github.com/apache/incubator-openwhisk-runtime-go/openwhisk.(*Executor).logger(0xc4200a1e50)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-runtime-go/openwhisk/executor.go:136 +0x15a
created by github.com/apache/incubator-openwhisk-runtime-go/openwhisk.(*Executor).Start
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-runtime-go/openwhisk/executor.go:186 +0x17a
rax    0xca
rbx    0x92b100
rcx    0x45c133
rdx    0x0
rdi    0x92b248
rsi    0x0
rbp    0x7fffab085300
rsp    0x7fffab0852b8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xffffffffffffffff
r13    0xa1
r14    0xa0
r15    0x100
rip    0x45c131
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/apache/incubator-openwhisk-runtime-go/openwhisk	600.004s
Test for github.com/apache/incubator-openwhisk-runtime-go/openwhisk finished, 1 completed, 1 failed
Generating HTML test report...
Finished generating test html results (0.083 secs) into: /home/travis/gopath/src/github.com/apache/incubator-openwhisk-runtime-go/.gogradle/reports/test
:test FAILED
:test (Thread[Task worker for ':',5,main]) completed. Took 10 mins 3.528 secs.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There are 1 failed tests. Please see /home/travis/gopath/src/github.com/apache/incubator-openwhisk-runtime-go/.gogradle/repor
```

**Comment by csantanapr** [comment]
@sciabarracom  Could you look into this failure?

**Comment by csantanapr** [comment]
Travis test are passing now
